# useful info here: https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions

name: MyWorkflowName
run-name: ${{ github.actor }} is my run-name

# here we can write anything from: https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows
on: [push, workflow_dispatch]




jobs:
  job1:
    uses: octo-org/example-repo/.github/workflows/called-workflow.yml@v1

  job2:
    runs-on: ubuntu-latest
    needs: job1
    steps:
      - run: echo ${{ needs.job1.outputs.firstword }} ${{ needs.job1.outputs.secondword }}