name: MyWorkflowName
run-name: ${{ github.actor }} is my run-name
on: [push]
jobs:
  job-one:
    runs-on: ubuntu-latest
    steps:
      - run: echo "This is job one."
jobs:
  job-two:
    runs-on: ubuntu-latest
    steps:
      - run: echo "This is job two."